services:
  node:
    container_name: node_docker_instance
    build:
      dockerfile: ./Dockerfile
    stdin_open: true
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - dist:/app/dist
volumes:
  node_modules:
  dist:
